// This file has been generated by Specta. DO NOT EDIT.

export type TauRpcApiInputTypes = { proc_name: "greet"; input_type: { __taurpc_type: string } }

export type TauRpcApiOutputTypes = { proc_name: "greet"; output_type: string }

const ARGS_MAP = {'':'{"greet":["name"]}'}
import { createTauRPCProxy as createProxy } from "taurpc"

export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)

type Router = {
	'': [TauRpcApiInputTypes, TauRpcApiOutputTypes],
}